### ISSUE TITLE
checklist 패키지 내에 Task 컨트롤러 구현

### ISSUE THREAD

**Issue by hwicode** [hwicode/schedule#16]
## Description

- [x] 과제 생성 기능 구현 및 테스트 작성
- [x] 과제 삭제 기능 구현 및 테스트 작성
- [x] 과제 진행 상태 변경 기능 구현 및 테스트 작성
- [x] 과제 어려움 점수 변경 기능 구현 및 테스트 작성

<br>

#### 컨트롤러에서 요청 받은 DTO를 서비스에서도 사용해도 될까?

+ 평소처럼 컨트롤러 DTO를 서비스 레이어에 사용했는데, 서비스 영역의 테스트가 변경되는 것을 보고 이상함을 느꼈다.

+ 이는 컨트롤러와 서비스간의 의존성을 의미했다.

+ 그래서 기존의 방식인 서비스 영역에서 엔티티와 id값 등의 정보를 직접 받는 방식으로 수정하고자 하였는데 컨트롤러에서 엔티티를 생성해야 하는 문제가 생겼다. 

+ 이번 기능의 경우 DailyChecklist에서 Task의 검증을 맡고 있어서 크게 상관이 없었지만 다른 기능의 경우 엔티티의 생성에 값 검증이 있을 수 있다. 

+ 이 때는 컨트롤러에서 엔티티의 생성을 담당하는 것은 계층의 역할에 맞지 않는다는 생각이 들었다.

+ 어쩔 때는 컨트롤러에서 엔티티가 생성되고, 다른 경우에는 서비스에서 엔티티가 생성되는 등 상황마다 엔티티의 생성 위치가 달라지는 것은 코드를 읽는 사람에게 혼란을 줄 수 있겠다는 생각이 들었다.

+ 그래서 결국에는 컨트롤러의 DTO를 서비스에도 사용하기로 하였다.

+ 물론 컨트롤러와 서비스의 의존성을 없애야 변경의 이유가 하나가 되기에 계층의 역할이 좀 더 명확하게 분리되겠지만 이렇게 되려면 서비스 영역을 위한 DTO를 따로 생성해야 한다.

+ 컨트롤러와 서비스가 1대1의 관계인 지금 이는 지나친 과정이라고 생각되었다.

<br>

** 참고 자료 : https://kafcamus.tistory.com/12

<br><br>

#### 도메인과 JPA

+ 위와 비슷한 경우가 도메인과 JPA에서도 나타난다.

+ 프로젝트를 시작할 때 도메인의 기능을 먼저 개발하고 이후에 데이터베이스와 연결하는 과정을 가졌는데 JPA로 인해 도메인에 메서드가 추가되고 JPA와 관련된 애노테이션들이 추가되었다.

+ 도메인에 JPA에 대한 의존성이 생기지만, 이 프로젝트에서는 JPA만을 사용하고 추후 변경 가능성도 없기 때문에 지금 이상의 처리가 지나치다고 판단하였다.
