### ISSUE TITLE
checklist 패키지 내에 커스텀 에러 생성

### ISSUE THREAD

**Issue by hwicode** [hwicode/schedule#18]
#### DailyChecklist

- [x] 과제의 이름이 중복되었습니다.
- [x] 알 수 없는 진행 상태입니다.
- [x] 과제를 찾을 수 없습니다.

#### Task
- [x] 서브 과제의 이름이 중복되었습니다.
- [x] 서브 과제를 찾을 수 없습니다.
- [x] 서브 과제가 전부 DONE 상태가 아닙니다.
- [x] 서브 과제가 전부 TODO 상태가 아닙니다.

#### DailyChecklistFindService
- [x] 체크 리스트가 존재하지 않습니다.
