### ISSUE TITLE
checklist 패키지 내에 커스텀 에러를 처리하는 컨트롤러 생성

### ISSUE THREAD

**Issue by hwicode** [hwicode/schedule#20]
## Description
+ 프로젝트에 커스텀 에러를 처리할 수 있는 GlobalExceptionHandler를 생성함

## Progress

- [x] @RestControllerAdvice를 사용해서 글로벌 에러를 처리하는 컨트롤러 생성
- [x] ChecklistBusinessException을 처리하는 로직 추가
- [x] ChecklistBusinessException이 발생했을 때 GlobalExceptionHandler가 처리하는지 테스트 작성
