### ISSUE TITLE
checklist 패키지 내에 엔드 투 엔트 테스트 작성

### ISSUE THREAD

**Issue by hwicode** [hwicode/schedule#23]
#### 과제 엔드 투 엔드 테스트

- [x] 과제 생성 요청 작성
- [x] 과제 삭제 요청 작성
- [x] 과제 진행 상태 변경 요청 작성
- [x] 과제 어려움 점수 변경 요청 작성

#### 서브 과제 엔드 투 엔드 테스트

- [x] 서브 과제 생성 요청 작성
- [x] 서브 과제 삭제 요청 작성
- [x] 서브 과제 진행 상태 변경 요청 작성

<br>

#### 참고 사항
changeSubTaskStatus 메서드의 리턴 값을 subTaskStatus라고 착각하였다. 그래서 이런 일의 재발을 방지하기 위해 Status를 TaskStatus와 SubTaskStatus로 나누었다.
