### ISSUE TITLE
checklist 패키지 내의 클래스들 리팩토링

### ISSUE THREAD

**Issue by hwicode** [hwicode/schedule#28]
## Progress
- [x] Status -> TaskStatus, SubTaskStatus로 변경
- [x] config 패키지와 exception_handler 패키지를 common 패키지로 옮김
- [x] taskName -> taskCheckerName, subTaskName -> subTaskCheckerName으로 변경
